#!/usr/bin/env bash

# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

set -eu

# Check format
nix develop -c mdl README.md
nix develop -c shellcheck say
nix develop -c nixfmt --check flake.nix default.nix
