#!/bin/bash

# TODO receive as parameter
MODEL=en_GB-alan-medium

if [[ $MODEL =~ -medium$ ]]; then
    AUDIO_RATE=22050
elif [[ $MODEL =~ -low$ ]]; then
    AUDIO_RATE=16000
else
    echo "Error: Invalid model name \"$MODEL\". It should end in \"-medium\" or \"-low\""
    exit 1
fi

# According to piper-tts, the model is downloaded automatically if not
# found, but it doesn't seem to work.  Look for it in the data folder.
SAY_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/say-tts"
MODELFILE="$SAY_DATA_DIR/${MODEL}.onnx"

if [[ ! -f "$MODELFILE" || ! -f "${MODELFILE}.json" ]]; then
   echo >&2 "Error: Either \"$MODELFILE\" or \"${MODELFILE}.json\" do not exist"
   echo >&2 "Download models from https://github.com/rhasspy/piper/blob/master/VOICES.md"
   exit 1
fi

if (( $# == 0 )); then
    cat -
else
    echo "$@"
fi | piper -m "$MODELFILE" --output_raw | aplay -r "$AUDIO_RATE" -f S16_LE -t raw -
