#!/bin/bash

# TODO receive as parameter
MODEL=en_GB-alan-medium
# TODO Guess from the model name: low = 16000, medium = 22050
AUDIO_RATE=22050
# According to piper, the model is downloaded automatically, but it
#doesn't seem to work.  Assume it is in the data folder for now.
SAY_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/say-tts"
MODELFILE="$SAY_DATA_DIR/${MODEL}.onnx"

echo "$@" | piper -m "$MODELFILE" --output_raw | aplay -r "$AUDIO_RATE" -f S16_LE -t raw -
