name: "Lints"
on:
  - pull_request
  - push
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: check shell script format
        run:  nix develop -c shellcheck say
      - name: check nix files format
        run:  nix develop -c nixfmt --check flake.nix default.nix
      - name: check README format
        run:  nix develop -c mdl README.md
      - name: run flake checks
        run:  nix flake check
